### ISSUE TITLE
Caso de Uso 07 - Encontrar Portão e Setor

### ISSUE THREAD

**Issue by Wicking** [LazyParking/lazyparking-server#20]
Pessoal, 
Não sei oque escrever nesse caso de uso, os outros dois eu fiz e já carreguei para o Google Drive.
Alguém se habilita para escrever esse caso de uso?

**Comment by FabioBeneditto** [comment]
Já resolvido lá mesmo.

**Comment by paulodiovani** [comment]
A intenção deste caso de uso era fazer um filtro de setores e entradas.
