### ISSUE TITLE
Criar página de listagem de vagas por setor

### ISSUE THREAD

**Issue by paulodiovani** [LazyParking/lazyparking-server#6]
A página deve exibir:

* Lista de setores
* Quantidade de vagas livres/total em cada setor

Esta _Feature_ implementa, em parte, os seguintes casos de uso:

* [UC04 - Gerenciar vagas](https://github.com/LazyParking/lazyparking-documentation/issues/12)
* [UC05 - Consultar vagas disponíveis](https://github.com/LazyParking/lazyparking-documentation/issues/13)
* [UC08 - Manter setores](https://github.com/LazyParking/lazyparking-documentation/issues/21) 

Obs:
Considerar dependência de #5.

**Comment by FabioBeneditto** [comment]
Essa issue acaba sendo atendida pelo nosso pull request #39 ?
